### ISSUE TITLE
Restrict CORS headers to *.stellar.org, localhost, and *.dev

### ISSUE THREAD

**Issue by nullstyle** [stellar/stellar-wallet#31]

**Comment by deckar01** [comment]
@nullstyle Is this something that should be implemented or configured through in stex?

**Comment by deckar01** [comment]
Discussed offline: Implement https://github.com/snd/url-pattern#match-domains in stex's CORS integration, then implement allowed origins in stellar-wallet's config.

**Comment by deckar01** [comment]
Now that CORS is fixed in stex (https://github.com/stellar/stex/pull/33), #32 can be reopened.

**Comment by nullstyle** [comment]
Fixed in #68 #69
